[POSTGRE_CONNECTION]
DB = your_database
USER = your_user
PASSWORD = your_password
HOST = your_host
PORT = 5432

[LOGGER]
LEVEL = INFO
FORMATTER = %(asctime)s:%(levelname)s:%(filename)s:%(message)s

[PROP_FILES]
PARAMS_PROP = conf/params
PROP_FACT_TABLE_A = conf/fact_table_a
PROP_FACT_TABLE_B = conf/fact_table_b

[INPUT_PG]
TABLE_EXEC_HISTORY = public.execution_history
TABLE_PROCESS_CATALOG = public.process_catalog

[IMPALA_CONNECTION]
HOST = impala.host.local
PORT = 21000

[KERBEROS]
USER = kerberos_user
